config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index', as: 'home'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'about', to: 'company_info#about', as:'about'
  get 'contact', to:'company_info#contact', as: 'contact'

  get 'products/:id', to: 'products#show', as: 'products', id: /\d+/

  get 'category/:id', to: 'categories#category_products', as: 'category', id: /\d+/

  get 'search', to:'products#search', as: 'search'

  get 'new', to:'products#new_products', as:'new'

  get 'updated', to:'products#updated_products', as:'updated'

  post 'cart/add_to_cart/:id', to: 'cart#add_to_cart', as:'add_to_cart', id: /\d+/

  get 'cart/cart_page', to: 'cart#cart_page', as: 'showCart'

  post 'cart/update/:id', to: 'cart#update', as: 'update', id: /\d+/

  post 'cart/delete/:id', to: 'cart#delete', as: 'delete', id: /\d+/

  resources :charges
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  validates :name, presence: true
end

app/models/company_info.rb
class CompanyInfo < ApplicationRecord

end

app/models/condition.rb
class Condition < ApplicationRecord
  has_many :products
  validates :name, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders
  validates :name, :password, :address, presence: true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order
  validates :quantity, :price, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :line_items
  validates :total, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :condition

  validates :name, :size, :color, :price, :image, presence: true

  mount_uploader :image, ImageUploader


    def self.keyword_search(keywords)
      keywords = "%" + keywords + "%"
      @result = Product.where("name LIKE ?", keywords)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
before_action :initial_session

   def add_to_cart
    @disable_search = true
     session[:cart] ||= {}
     session[:cart][params[:id]] ||= 0
     session[:cart][params[:id]] += 1

     redirect_to action:"cart_page"

   end

   def cart_page
    @disable_search = true
    @categories = Category.all
    session[:cart] ||= {}
   end

   private
   def initial_session
     session[:cart] ||= {}
   end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def category_products
    @categories = Category.all
    @category_products = Product.where(category_id: params[:id])
  end


end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
end

def create
  # Amount in cents
  @amount = 500

  customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => 'Rails Stripe customer',
    :currency    => 'usd'
  )

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to home_url
end
end

app/controllers/company_info_controller.rb
class CompanyInfoController < ApplicationController
  def about
    @categories = Category.all
    @about = CompanyInfo.first
    @disable_search = true;
  end

  def contact
    @categories = Category.all
    @about = CompanyInfo.first
    @disable_search = true;
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.order("name").page(params[:page]).per(6)
    @categories = Category.all
  end

  def show
    @product = Product.find(params[:id])
    @disable_search = true
      @categories = Category.all
  end

  def search
    @categories = Category.all
    if params[:categories] != ""
      @result =Product.keyword_search(params[:search_keywords]).where("category_id = ?", params[:categories]).page(params[:page]).per(6)
    else
      @result =Product.keyword_search(params[:search_keywords]).page(params[:page]).per(6)
    end
  end

  def new_products
    @categories = Category.all
    @new = Product.order("created_at DESC").page(params[:page]).per(6)
  end

  def updated_products
    @categories = Category.all
    @updated = Product.order("updated_at DESC").page(params[:page]).per(6)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/company_info_helper.rb
module CompanyInfoHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart/cart_page.html.erb
<div class="container">
    <%= debug session[:cart] %>
<table>
  <% session[:cart].each do|id, quantity| %>
    <% item = Product.where(:id => id).first %>
    <tr>
      <td><img src="<%=item.image %>"></td>
       <td><%= item.name %></td>

       <td><%=form_tag(update_path(id), method: :post) do%>
         <div class="col-md-12">
              <input type=number value=<%=quantity%> name=quantity max=2 min=0  />
              <td>
            <%= submit_tag("Update Quantity")%>
          </td>
          </div>
            <%end%>
       </td>
       <td><%=form_tag(delete_path(id), method: :post) do%>

            <%= submit_tag("Delete")%>
            <%end%>
       </td>
    </tr>
    <% end %>
</table>

<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>
</div>

app/views/categories/category_products.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Shop Homepage - Start Bootstrap Template</title>
  </head>
  <body>
    <!-- Page Content -->
    <div class="container">


        <div class="col-lg-9">

          <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
          <div class="row">
            <% @category_products.each do|product|%>
            <div class="col-lg-4 col-md-6 mb-4">
              <div class="card h-100">
              <a href="/products/<%= product.id%>"><img class="card-img-top" src="<%=product.image %>" alt=""></a>
                <div class="card-body">
                  <h4 class="card-title">
                    <a href="/products/<%= product.id%>"><%= product.name%></a>
                    <!-- <%= link_to product.name,products_path(product)%> -->
                  </h4>

                  <p><%= product.description %></p>
                  <h5><%= number_to_currency product.price%></h5>
                  <!-- <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!</p> -->
                </div>
                <div class="card-footer">
                  <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                </div>
              </div>
            </div>
            <% end %>
          </div>
          <!-- /.row -->
        </div>
        <!-- /.col-lg-9 -->
      </div>
    <!-- /.container -->
 </div>

    <!-- Bootstrap core JavaScript -->
    <script src="/suit_shop/vendor/jquery/jquery.min.js"></script>
    <script src="/suit_shop/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  </body>

</html>

app/views/charges/create.html.erb
<h2>Thanks!</h2>

app/views/company_info/about.html.erb

<html>
<body>
<div class="container" style="padding-top: 20px">
  <h1>About us</h1>
  <p><%=@about.description%></p>

</div>
</body>
</html>

app/views/company_info/contact.html.erb
<html>
<body>
<div class="container" style="padding-top: 20px">
  <h1>Contact Us</h1>
  <p>Phone: <%=@about.number%></p>
    <p>Email: <%=@about.email%></p>
      <p>Address: <%=@about.address%></p>

</div>
</body>
</html>

app/views/products/index.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Shop Homepage - Start Bootstrap Template</title>
  </head>
  <body>
    <!-- Page Content -->
    <div class="container">


        <div class="col-lg-9">

          <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
          <div class="row">
            <% @products.each do|product|%>
            <div class="col-lg-4 col-md-6 mb-4">
              <div class="card h-100">
                <a href="/products/<%= product.id%>"><img class="card-img-top" src="<%=product.image %>" alt=""></a>
                <div class="card-body">
                  <h4 class="card-title">
                    <a href="/products/<%= product.id%>"><%= product.name%></a>
                    <!-- <%= link_to product.name,products_path(product)%> -->
                  </h4>
                  <h5><%= number_to_currency product.price%></h5>
                  
                  <!-- <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!</p> -->
                </div>
                <div class="card-footer">
                  <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                </div>
              </div>
            </div>
            <% end %>
          </div>
          <%= paginate @products %>
          <!-- /.row -->
        </div>
        <!-- /.col-lg-9 -->
      </div>
    <!-- /.container -->
 </div>

    <!-- Bootstrap core JavaScript -->
    <script src="/suit_shop/vendor/jquery/jquery.min.js"></script>
    <script src="/suit_shop/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  </body>

</html>

app/views/products/new_products.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Shop Homepage - Start Bootstrap Template</title>
  </head>
  <body>
    <!-- Page Content -->
    <div class="container">


        <div class="col-lg-9">

          <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
          <div class="row">
            <% @new.each do|product|%>
            <div class="col-lg-4 col-md-6 mb-4">
              <div class="card h-100">
              <a href="/products/<%= product.id%>"><img class="card-img-top" src="<%=product.image %>" alt=""></a>
                <div class="card-body">
                  <h4 class="card-title">
                    <a href="/products/<%= product.id%>"><%= product.name%></a>
                    <!-- <%= link_to product.name,products_path(product)%> -->
                  </h4>

                  <p><%= product.description %></p>
                  <h5><%= number_to_currency product.price%></h5>
                  <!-- <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!</p> -->
                </div>
                <div class="card-footer">
                  <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                </div>
              </div>
            </div>
            <% end %>
          </div>
          <!-- /.row -->

          <%= paginate @new %>
        </div>
        <!-- /.col-lg-9 -->
      </div>
    <!-- /.container -->
 </div>

    <!-- Bootstrap core JavaScript -->
    <script src="/suit_shop/vendor/jquery/jquery.min.js"></script>
    <script src="/suit_shop/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  </body>

</html>

app/views/products/search.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Shop Homepage - Start Bootstrap Template</title>
  </head>
  <body>
    <!-- Page Content -->
    <div class="container">


        <div class="col-lg-9">

          <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
          <div class="row">
            <% @result.each do|product|%>
            <div class="col-lg-4 col-md-6 mb-4">
              <div class="card h-100">
                <a href="/products/<%= product.id%>"><img class="card-img-top" src="<%=product.image %>" alt=""></a>
                <div class="card-body">
                  <h4 class="card-title">
                    <a href="/products/<%= product.id%>"><%= product.name%></a>
                    <!-- <%= link_to product.name,products_path(product)%> -->
                  </h4>
                  <h5><%= number_to_currency product.price%></h5>
                  <!-- <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!</p> -->
                </div>
                <div class="card-footer">
                  <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                </div>
              </div>
            </div>
            <% end %>
          </div>
          <%= paginate @result %>
          <!-- /.row -->
        </div>
        <!-- /.col-lg-9 -->
      </div>
    <!-- /.container -->
 </div>

    <!-- Bootstrap core JavaScript -->
    <script src="/suit_shop/vendor/jquery/jquery.min.js"></script>
    <script src="/suit_shop/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  </body>

</html>

app/views/products/show.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Shop Homepage - Start Bootstrap Template</title>
  </head>
  <body>
    <!-- Page Content -->
    <div class="container">


        <div class="col-lg-9">


          <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
          <div class="row">


            <div class="col-lg-4 col-md-6 mb-4">
              <div class="card h-100">
              <a href="/products/<%= @product.id%>"><img class="card-img-top" src="<%=@product.image %>" alt=""></a>
                <div class="card-body">
                  <h4 class="card-title">
                    <a href="/products/<%= @product.id%>"><%= @product.name%></a>

                  </h4>
                  <p><%= @product.description %></p>
                  <h5><%= number_to_currency @product.price%></h5>
                  <!-- <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!</p> -->
                </div>
                <div class="card-footer">
                  <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                </div>
              </div>
            </div>
          </div>
          <!-- /.row -->
          <%=form_tag(add_to_cart_path(@product.id), method: :post) %>
          <%= submit_tag("Add") %>
          </div>
          <!-- /.col

        <!-- /.col-lg-9 -->
      </div>
    <!-- /.container -->
 </div>

    <!-- Bootstrap core JavaScript -->
    <script src="/suit_shop/vendor/jquery/jquery.min.js"></script>
    <script src="/suit_shop/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  </body>

</html>

app/views/products/updated_products.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Shop Homepage - Start Bootstrap Template</title>
  </head>
  <body>
    <!-- Page Content -->
    <div class="container">


        <div class="col-lg-9">

          <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
          <div class="row">
            <% @updated.each do|product|%>
            <div class="col-lg-4 col-md-6 mb-4">
              <div class="card h-100">
              <a href="/products/<%= product.id%>"><img class="card-img-top" src="<%=product.image %>" alt=""></a>
                <div class="card-body">
                  <h4 class="card-title">
                    <a href="/products/<%= product.id%>"><%= product.name%></a>
                    <!-- <%= link_to product.name,products_path(product)%> -->
                  </h4>

                  <p><%= product.description %></p>
                  <h5><%= number_to_currency product.price%></h5>
                  <!-- <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!</p> -->
                </div>
                <div class="card-footer">
                  <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                </div>
              </div>
            </div>
            <% end %>
          </div>
          <!-- /.row -->
        </div>
        <!-- /.col-lg-9 -->
      </div>
    <!-- /.container -->
 </div>

    <!-- Bootstrap core JavaScript -->
    <script src="/suit_shop/vendor/jquery/jquery.min.js"></script>
    <script src="/suit_shop/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  </body>

</html>