config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index', as: 'home'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'about', to: 'company_info#about', as:'about'
  get 'contact', to:'company_info#contact', as: 'contact'

  get 'products/:id', to: 'products#show', as: 'products', id: /\d+/

  get 'category/:id', to: 'categories#category_products', as: 'category', id: /\d+/

  get 'search', to:'products#search', as: 'search'

  get 'new', to:'products#new_products', as:'new'

  get 'updated', to:'products#updated_products', as:'updated'

  post 'cart/add_to_cart/:id', to: 'cart#add_to_cart', as:'add_to_cart', id: /\d+/

  get 'cart/cart_page', to: 'cart#cart_page', as: 'showCart'

  post 'cart/update/:id', to: 'cart#update', as: 'update', id: /\d+/

  post 'cart/delete/:id', to: 'cart#delete', as: 'delete', id: /\d+/

  resources :charges
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  validates :name, presence: true
end

app/models/company_info.rb
class CompanyInfo < ApplicationRecord

end

app/models/condition.rb
class Condition < ApplicationRecord
  has_many :products
  validates :name, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders
  validates :name, :password, :address, presence: true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order
  validates :quantity, :price, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :line_items
  validates :total, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :condition

  validates :name, :size, :color, :price, :image, presence: true

  mount_uploader :image, ImageUploader


    def self.keyword_search(keywords)
      keywords = "%" + keywords + "%"
      @result = Product.where("name LIKE ?", keywords)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
before_action :initial_session

   def add_to_cart
    @disable_search = true
     session[:cart] ||= {}
     session[:cart][params[:id]] ||= 0
     session[:cart][params[:id]] += 1

     redirect_to action:"cart_page"

   end

   def cart_page
    @disable_search = true
    @categories = Category.all
    session[:cart] ||= {}
   end

   private
   def initial_session
     session[:cart] ||= {}
   end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def category_products
    @categories = Category.all
    @category_products = Product.where(category_id: params[:id])
  end


end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
end

def create
  # Amount in cents
  @amount = 500

  customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => 'Rails Stripe customer',
    :currency    => 'usd'
  )

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to home_url
end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.order("name").page(params[:page]).per(6)
    @categories = Category.all
  end

  def show
    @product = Product.find(params[:id])
    @disable_search = true
      @categories = Category.all
  end

  def search
    @categories = Category.all
    if params[:categories] != ""
      @result =Product.keyword_search(params[:search_keywords]).where("category_id = ?", params[:categories]).page(params[:page]).per(6)
    else
      @result =Product.keyword_search(params[:search_keywords]).page(params[:page]).per(6)
    end
  end

  def new_products
    @categories = Category.all
    @new = Product.order("created_at DESC").page(params[:page]).per(6)
  end

  def updated_products
    @categories = Category.all
    @updated = Product.order("updated_at DESC").page(params[:page]).per(6)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/company_info_helper.rb
module CompanyInfoHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThriftCollection</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    <!-- Custom styles for this template -->
    <link href="css/shop-homepage.css" rel="stylesheet">

  </head>

  <body>
    <%= render partial: 'partials/header' %>
  <div class="row">
    <%= yield %>
    <%= render partial: 'partials/search' unless @disable_search%>
  </div>

    <!-- Navigation -->

      <%= render partial: 'partials/footer' %>

  </body>
</html>

app/views/partials/_footer.html.erb
<!-- Footer -->
<footer class="py-5 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy; Your Website 2017</p>
  </div>
  <!-- /.container -->
</footer>

app/views/partials/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <%= form_tag search_path, method: 'get' do %>
          <%= text_field_tag :search_keywords %>
          <%= select_tag "categories",
                        options_from_collection_for_select(@categories, "id","name"),
                        include_blank: true %>
          <%= submit_tag "Search" %>
        <% end %>


      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <%= link_to 'Home', home_path, :class => "nav_link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'About', about_path, :class => "nav_link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Contact', contact_path, :class => "nav_link" %>
          </li>
        </ul>
        <li class="nav-item">
          <%= link_to 'Cart', showCart_path, :class => "nav_link" %>
        </li>
      </div>
    </div>
  </nav>
</header>

app/views/partials/_search.html.erb
<div class="col-lg-3">

  <h1 class="my-4">Shop Name</h1>
  <div class="list-group">
    <% @categories.each do |cat| %>
    <%= link_to cat.name, category_path(cat), :class => "list-group-item" %>
    <% end %>
    <%= link_to 'New', new_path, :class => "list-group-item" %>

    <%= link_to 'Updated', updated_path, :class => "list-group-item" %>
  </div>

</div>